djangoProject1/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('gameFanWebsite.urls')),
]

gameFanWebsite/urls.py
from . import views
from django.urls import path


app_name = 'gameFanWebsite'
urlpatterns = [
    path('', views.indexView, name="index"),
    path('rules/', views.rulesView, name="rules"),
    path('notables/<int:notableIndex>/', views.notablesDetail, name="notablesDetail"),
    path('notables/', views.notablesList, name="notablesList"),
    path('externalLinks/', views.externalLinks, name="externalLinks"),
]

gameFanWebsite/models.py
from django.db import models

# Create your models here.

gameFanWebsite/views.py
import random

from django.http import HttpResponse, Http404
from django.shortcuts import render, redirect

# Create your views here.

samplePicList = [
        'https://cdn.pixabay.com/photo/2016/02/15/14/45/playing-cards-1201257_1280.jpg',
        'https://img.freepik.com/free-vector/playing-casino-card-chips-and-dice-flying-background_1017-30143.jpg?t=st=1658662634~exp=1658663234~hmac=c8db1caf344d477fbb32c3714761570309f901cd2082912beb17ecb45ac1146a&w=1800',
        'https://img.freepik.com/premium-photo/poker-player-showing-a-pair-of-aces_306105-9.jpg?w=1800',
        'https://img.freepik.com/premium-photo/gambling-close-up-cards-for-playing-poker-on-a-gaming-table-in-a-casino_391052-1268.jpg?w=1800',
    ]

playerList = [
    {
        "name": "Bryn Kenney",
        "pic": "https://media.cardplayer.com/assets/000/026/576/BRYN_Q_A_FEAT.jpg",
        "ranking": 1,
        "description": "Bryn KenneyはTriton Pokerのライブポーカートーナメント史上最大の＄20,563,324を受け取った経験があります。プロポーカープレイヤーになる前に世界で有名なマジック・ザ・ギャザリングというトレーディングカードゲームを熱狂的にプレイしていたことで有名です。",
    },
    {
        "name": "Justin Bonomo",
        "pic": "https://www.4media.tv/wp-content/uploads/2021/12/39751991242_5ae6e8fa09_b-1024x683-1.jpg",
        "ranking": 2,
        "description": "Justin Bonomoもプロポーカープレイヤーになる前は世界で有名なマジック・ザ・ギャザリングのプレイヤーとして活躍していました。彼は500ドルから始めて10000ドルにし、そのお金を軍資金に、全仏オープンでのEPTの初年度に史上最年少で4位になった経歴を持っています。",
    },
    {
        "name": "Daniel Negreanu",
        "pic": "https://cdn.pocketfives.com/p5wp/2019/04/daniel-negreanu-leaves-team-pokerstars.jpg",
        "ranking": 3,
        "description": "Daniel Negreanuは6つのWSOPのブレスレットと2つのWPTチャンピョンシップを勝ち取ったプロポーカープレイヤーです。また、2004年と2013年にWSOP年間最優秀プレイヤーに選ばれ、世界で賞賛を2回以上受けた唯一のプレイヤーになりました。",
    },
]

externalLinksList = [
    {
        "name": "任天堂",
        "url": "https://www.nintendo.co.jp/others/playing_cards/howtoplay/poker/index.html"
    },
    {
        "name": "全日本ポーカー選手権",
        "url": "https://www.ajpc.jp/about-poker/"
    },
]

def indexView(request):
    ctx = {"pic": random.choice(samplePicList)}
    return HttpResponse(render(request, 'index.html', ctx))


def rulesView(request):
    return HttpResponse(render(request, 'rules.html'))

def notablesDetail(request, notableIndex):
    try:
        ctx = {
            "num": notableIndex,
            "data": playerList[notableIndex-1]
               }
    except:
        raise Http404("選手は存在しません")
    return HttpResponse(render(request, 'notablesDetail.html', ctx))


def notablesList(request):
    ctx = {"data": playerList}
    return HttpResponse(render(request, 'notables.html', ctx))


def externalLinks(request):
    ctx = {"data": externalLinksList}
    return HttpResponse(render(request, 'externalLinks.html', ctx))

templates/base.html
<!DOCTYPE html>
<html lang="ja">

<head>
    <meta charset="UTF-8">
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <title>{% block title %}{% endblock %}</title>
</head>

<body>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class=>
                <ul class="navbar-nav m-2">
                    <li class="nav-item m-2"><a href={% url 'gameFanWebsite:index' %}>Home</a></li>
                    <li class="nav-item m-2"><a href={% url 'gameFanWebsite:rules' %}>Rule</a></li>
                    <li class="nav-item m-2"><a href={% url 'gameFanWebsite:notablesList' %}>Notables</a></li>
                    <li class="nav-item m-2"><a href={% url 'gameFanWebsite:externalLinks' %}>Link</a></li>
                </ul>
            </div>
        </nav>
    <div class="p-3">
        {% block content %}{% endblock %}
    </div>
</body>

    <footer>
        <p>© 2022 GameFanWebsite All Rights Reserved.</p>
    </footer>
</html>

templates/externalLinks.html
{% extends "base.html" %}

{% block title %}externalLinks{% endblock %}

{% block content %}
    <h1>ExternalLinks</h1>
    {% for link in data %}
        <ul>
            <li>
                <p>{{ link.name }}: <a href="{{ link.url }}">{{ link.url }}</a></p>
            </li>
        </ul>
    {% endfor %}
{% endblock %}

templates/index.html
{% extends "base.html" %}
{% load static %}

{% block title %}Home{% endblock %}

{% block content %}
    <h1>Home</h1>
    <p>pokerのルールと有名なプレイヤーについて紹介するサイトです。</p>
    <img src="{{ pic }}" width="500" height="auto" alt="gameName">
{% endblock %}

templates/notables.html
{% extends "base.html" %}

{% block title %}notables{% endblock %}

{% block content %}
    <h1>Notable Players</h1>
    {% for player in data %}
        <ul>
            <a href="{{ player.ranking }}"><li><p>{{ player.name }}</p></li>
            <img src="{{ player.pic }}" width="100" height="auto">
            </a>
        </ul>
    {% endfor %}
{% endblock %}

templates/notablesDetail.html
{% extends "base.html" %}

{% block title %}notablesDetail{% endblock %}

{% block content %}
    <h1>Player Detail</h1>
    <img src="{{ data.pic }}" width="300" height="auto">
    <p>Name: {{ data.name }}</p>
    <p>Current Ranging: {{ data.ranking }}</p>
    <p>{{ data.description }}</p>
{% endblock %}

templates/rules.html
{% extends 'base.html' %}

{% block title %}rules{% endblock %}

{% block content %}
    <h1>ルール</h1>
        <p>ポーカーの遊び方の一つである、ドローポーカーのルールを説明します。最初のラウンドでベットをし、その後のラウンドで不要なカードを交換したら再度ベットをし、勝敗を決するというのが基本形です。相手のカードが全く見えないので、他のルールよりも比較的駆け引きがしにくいゲームと言えるかもしれません。</p>
    <h2>手札の強さ</h2>
        <p>強い順に説明します。</p>
        <p>ロイヤルストレートフラッシュ<br>同種札で数字が1番高い順位にそろったもので、10・J・Q・K・Aとなります</p>
        <img src="https://www.card-asobi.com/wp8/wp-content/uploads/2018/04/straight-flush-hi-1024x273.gif" width="500" height="auto">
        <p>ストレート・フラッシュ<br>同種札で数字が順番に並んでいるものです。 ただし……K・A・2……とは続きません</p>
        <img src="https://www.card-asobi.com/wp8/wp-content/uploads/2018/03/straight-flush-high-1024x273.gif" width="500" height="auto">
        <p>フォア・カード<br>同位札が4枚そろったものです。</p>
        <img src="https://www.card-asobi.com/wp8/wp-content/uploads/2018/04/four-of-a-kind-hi-1024x278.gif" width="500" height="auto">
        <p>フルハウス<br>同位札が3枚と、同位札が2枚の役です。 同じ役同士では3枚組で比較し、順位の高いほうが勝ちです。</p>
        <img src="https://www.card-asobi.com/wp8/wp-content/uploads/2018/04/full-house-hi-1024x279.gif" width="500" height="auto">
        <p>フラッシュ<br>同種札が5枚そろったものです。</p>
        <img src="https://www.card-asobi.com/wp8/wp-content/uploads/2018/04/flush-higif-1024x279.gif" width="500" height="auto">
        <p>ストレート<br>スートの種類に関係なく、5枚のカードの数字が続いているものです。</p>
        <img src="https://www.card-asobi.com/wp8/wp-content/uploads/2018/04/straight-hi-1024x279.gif" width="500" height="auto">
        <p>スリーカード<br>同位札が3枚そろったものです。</p>
        <img src="https://www.card-asobi.com/wp8/wp-content/uploads/2018/03/three-of-a-kind-hi-1024x279.gif" width="500" height="auto">
        <p>ツウ・ペア<br>2枚ずつの同位札が2組。同じ役同士では高いほうのペアを比較して、順位の高いほうが勝ち。それも同じなら低いほうのペアを比較して、順位の高いほうが勝ち。またそれも同じなら、高いほうのペアで♠を持っている人が勝ちとなります。</p>
        <img src="https://www.card-asobi.com/wp8/wp-content/uploads/2018/03/two-of-a-kind-hi-1024x279.gif" width="500" height="auto">
        <p>ワン・ペア<br>同位札が2枚そろったもの。同じ役同士ではペアを比較して、順位の高いほうが勝ち。それも同じなら、ペアの中で♠を持っている人が勝ちとなります。</p>
        <img src="https://www.card-asobi.com/wp8/wp-content/uploads/2018/03/one-pair-hi-1024x279.gif" width="500" height="auto">
{% endblock %}